In [5]:
#1
import numpy as np

In [ ]:
# import sys
# print(sys.executable)


c:\Users\BAPS\Documents\GitHub\Devsoc_assignments\.venv\Scripts\python.exe


In [ ]:
#2
print(np.__version__)

2.4.0


In [ ]:
#3
a = np.zeros(10)

In [ ]:
#4
a = np.array([[2,3,4], 
              [5,6,7]], dtype = 'int64')
print(a.nbytes) #why? 6 * 8 bytes (1 bit) = 48 bytes

48


In [ ]:
#5


In [21]:
#6
a = np.zeros(10)
a[4]  = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#7
a = np.random.randint(10,50 , size = (1,10)) #does not include 50.
#can also use np.arange(10,50)
print(a)

[[12 17 31 14 38 43 45 34 47 15]]


In [ ]:
#8
a = np.array = ([1,2,3,4,5])
print(a)
a_rev = np.flip(a)
print(a_rev)
    

In [66]:
#alt for 8:
a = np.array = ([1,2,3,4,5])
a = a[ : : - 1] #stars from the end since step = -1
print(a)


[5, 4, 3, 2, 1]


In [ ]:
#9 
a = np.random.randint(0,9, size = (3,3))
print(a)
#alt --> using np.arange(0,9).reshape(3,3)

[[8 4 2]
 [8 5 8]
 [6 5 2]]


In [7]:
#10
a = np.array([1,2,0,0,4,0])
for i in a: 
    if i !=0:
        print(f"{i}")

1
2
4


In [ ]:
#11
a = np.identity(3) #by default the type is float 64 --> reason for decimals.
#print(a.nbytes)
print(a)


72
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
#12
a = np.random.rand(3,3,3) #note: we dont need to provide size here since .rand() only has values [0,1)
print(a)

[[[0.52128032 0.55168458 0.81328916]
  [0.19438815 0.65329558 0.30273085]
  [0.20156727 0.31890211 0.36636444]]

 [[0.01632069 0.78377681 0.18622728]
  [0.81006619 0.62106325 0.06607755]
  [0.73295759 0.68204539 0.15263425]]

 [[0.73263327 0.14344832 0.49310423]
  [0.44399757 0.37016591 0.4680966 ]
  [0.29905469 0.92482493 0.94029539]]]


In [22]:
#13
a = np.random.rand(10,10)
max = np.max(a)
min = np.min(a)
print(f"{max}, {min}")

0.9987868197618825, 0.015857168730381344


In [42]:
#14
a = np.random.rand(30) #pass the shape of the array
#print(a.shape)
sum = 0
for i in a:
    sum += i/30
print(f"{sum}")

0.46935116967311596


In [50]:
#alt for 14 -->
a = np.random.rand(30)
mean = a.mean()
print(f"{mean}")

0.5645526444840492


In [68]:
#15
a = np.ones((5,5), dtype = 'int64')
a[1:-1, 1:-1] = 0
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
#16
a = np.ones((10,10), dtype = 'int64')
a[: , [0,-1]] = 0
a[[0,-1] , :] = 0
print(a)

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [75]:
#alt for 16:
a = np.ones((10,10), dtype = 'int64')
np.pad(a, pad_width=1, mode = 'constant', constant_values=0)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
#17
print(0 * np.nan) #
print(np.nan == np.nan) #
print(np.inf > np.nan) #
print(np.nan - np.nan) #
print(np.nan in set([np.nan])) #didnt understand 
print(0.3 == 3 * 0.1) #

nan
False
False
nan
True
False


In [ ]:
#18 
a = np.diag(1 + np.arange(4), k = -1) #automatically makes a 5x5 matrix
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [99]:
#19
a = np.zeros((8,8), dtype = 'int64')
a[0: : 2, 0: : 2] = 1
a[1: : 2, 1: : 2] = 1
print(a)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [103]:
#20
a = np.unravel_index(99, (6,7,8)) #unravel_index(element number, A.shape), where A is the matrix
print(a)

(np.int64(1), np.int64(5), np.int64(3))


In [ ]:
#21
a = np.tile([[0,1],
             [1,0]], (5,5)) #repeats row 5 times and col 5 times
print(a)



[[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]]


In [ ]:
#22
